### ISSUE TITLE
Save registrarAddress as type Registrar

### ISSUE THREAD

**Issue by naterush** [EthHead/ens.trade#1]
In the first line of newListing function, registrarAddress is cast to type Registrar. Saving as type Registrar in the constructor would eliminate (minor) gas cost, as this would no longer have to be cast on every single function call.

**Comment by EthHead** [comment]
Thanks. Fixed in https://github.com/EthHead/ens.trade/commit/4948c336442a8740c0dd02b155b2ebd3a508e9a3
