### ISSUE TITLE
Capitalizing Events

### ISSUE THREAD

**Issue by naterush** [EthHead/ens.trade#2]
This is just a style note, but consider capitalizing first letter of all events. This makes it harder to confuse them with function calls. Generally considered good style.

**Comment by EthHead** [comment]
Thanks, fixed in. https://github.com/EthHead/ens.trade/commit/4948c336442a8740c0dd02b155b2ebd3a508e9a3

Feel free to PM me an ether address so I can give you some eth for your help!

**Comment by naterush** [comment]
Awesome! Will do in the future - after I try to help resolve other issues (+ possibly write tests - if it would be helpful. I'm looking for more practice). Thanks :)
